development:
  adapter: postgresql
  encoding: utf8
  database: abhshoe_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: utf8
  database: abhshoe_test
  pool: 5
  username: postgres
  password: postgres